# Generated by Django 4.2.7 on 2023-12-09 08:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_body2_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
