# Generated by Django 4.2.7 on 2023-12-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_body2_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('ip', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IP',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ip_like',
            field=models.ManyToManyField(to='blog.ip'),
        ),
    ]
